apiVersion: v1
kind: Template
metadata:
  name: user-api-buildconfig
  annotations:
    description: >
      This is Thoth User API BuildConfig, this template is meant to be used by
      Bots, but could also be used by humans...
    openshift.io/display-name: 'Thoth Core: User API BuildConfig'
    version: 0.4.2
    tags: thoth,thoth-user-api,ai-stacks,aistacks
    template.openshift.io/documentation-url: https://github.com/Thoth-Station/
    template.openshift.io/long-description: >
      This is Thoth User API BuildConfig, this template is meant to be used
      by Bots, but could also be used by humans...
    template.openshift.io/provider-display-name: Red Hat, Inc.
  labels:
    template: user-api-buildconfig
    app: thoth
    component: user-api

objects:
  - apiVersion: build.openshift.io/v1
    kind: BuildConfig
    metadata:
      name: user-api
      labels:
        app: thoth
        component: user-api
    spec:
      successfulBuildsHistoryLimit: 1
      failedBuildsHistoryLimit: 2
      resources:
        requests:
          cpu: 500m
          memory: 512Mi
        limits:
          cpu: 1000m
          memory: 768Mi
      output:
        to:
          kind: ImageStreamTag
          name: "user-api:${IMAGE_STREAM_TAG}"
      source:
        type: Git
        git:
          uri: ${GITHUB_URL}
          ref: ${GITHUB_REF}
      strategy:
        type: Source
        sourceStrategy:
          from:
            kind: ImageStreamTag
            name: python-36-centos7:latest
          env:
            - name: ENABLE_PIPENV
              value: '1'
            - name: UPGRADE_PIP_TO_LATEST
              value: ''
            - name: WEB_CONCURRENCY
              value: '4'
      triggers:
        - type: ImageChange
          imageChange: {}

parameters:
  - description: Name of the github repository for Thoth's User API
    displayName: Git Repository
    required: true
    name: GITHUB_URL
    value: 'https://github.com/thoth-station/user-api'

  - description: Git reference to be used for Thoth's User API
    displayName: Git Reference
    required: true
    name: GITHUB_REF
    value: 'master'

  - description: >
      Tag of the output ImageStream the resulting container image should go to
    displayName: ImageStream Tag
    required: true
    name: IMAGE_STREAM_TAG
    value: 'latest'
